### ISSUE TITLE
Can you please increase dependencies version in Cargo.toml

### ISSUE THREAD

**Issue by incker** [magiclen/map-to-javascript-html#1]
Can you please increase dependencies version in Cargo.toml

`lazy_static = "1.1"  →  lazy_static = "1.4"` Or maybe `lazy_static = "1"` if you want

Forward thank you

**Comment by magiclen** [comment]
Could you explain why you need that?

**Comment by incker** [comment]
just minimize variety of dependencies that crates need
It is not urgent, maybe when you will do next fixes, you'll remember that someone asked)

Or any version like `"~1"`, `"^1"`, `"1.*"`

**Comment by incker** [comment]
I am sorry, `lazy_static = "1.1"` is a same as `lazy_static = "^1.1"`
So no fix needed..

**Comment by magiclen** [comment]
`1.1` is interpreted the same way as if we had specified  `^1.1`.

If you need to upgrade the `lazy_static` crate and other crates, just run `cargo update`.
